// src/SendMenu.tsx
import { useEffect, useState } from "react";
import { writeText } from "@tauri-apps/plugin-clipboard-manager";
import { open as openDialog, save as saveDialog } from "@tauri-apps/plugin-dialog";
import { openUrl } from "@tauri-apps/plugin-opener";
import { api, errorText, type Note } from "./api";
import { Icon, type IconName } from "./Icons";
import { asPrompt, toPlainText } from "./markdown";

/** Claude Desktop truncates `q` at ~14k characters; stay well under for every target. */
const MAX_URL_PROMPT = 7000;
const IS_MAC = navigator.userAgent.includes("Mac");

type FolderTarget = "claude-terminal" | "codex-terminal" | "claude-desktop-code";

const FOLDER_TARGET_LABELS: Record<FolderTarget, string> = {
  "claude-terminal": "Claude Code in a terminal",
  "codex-terminal": "Codex in a terminal",
  "claude-desktop-code": "Claude Code in the Claude app",
};

interface Props {
  note: Note;
  body: string;
  /** Save pending edits first, so handoffs that read the note file see them. */
  flush: () => Promise<void>;
  onClose: () => void;
  toast: (message: string, error?: boolean) => void;
}

function basename(path: string) {
  return path.replace(/[\\/]+$/, "").split(/[\\/]/).pop() || path;
}

export default function SendMenu({ note, body, flush, onClose, toast }: Props) {
  const [folderTarget, setFolderTarget] = useState<FolderTarget | null>(null);
  const [recent, setRecent] = useState<string[]>([]);

  useEffect(() => {
    api.getConfig().then((c) => setRecent(c.recent_folders ?? []));
  }, []);

  const run = async (action: () => Promise<void>) => {
    try {
      await action();
      onClose();
    } catch (e) {
      toast(errorText(e), true);
    }
  };

  const copy = (text: string, message: string) =>
    run(async () => {
      await writeText(text);
      toast(message);
    });

  /** Opens a prefilled URL; long notes go on the clipboard instead. */
  const openPrefilled = (buildUrl: (prompt: string) => string, bareUrl: string, app: string) =>
    run(async () => {
      const prompt = asPrompt(note, body);
      if (prompt.length > MAX_URL_PROMPT) {
        await writeText(prompt);
        await openUrl(bareUrl);
        toast(`Note is long, so it's on your clipboard — paste it into ${app}`);
      } else {
        await openUrl(buildUrl(encodeURIComponent(prompt)));
        toast(`Opened in ${app} — review and send`);
      }
    });

  const rememberFolder = async (folder: string) => {
    const config = await api.getConfig();
    const folders = [folder, ...config.recent_folders.filter((f) => f !== folder)].slice(0, 6);
    await api.setConfig({ ...config, recent_folders: folders });
  };

  const openWithFolder = (target: FolderTarget, folder: string) =>
    run(async () => {
      await flush();
      if (target === "claude-desktop-code") {
        const prompt = asPrompt(note, body);
        if (prompt.length > MAX_URL_PROMPT) await writeText(prompt);
        const q = prompt.length > MAX_URL_PROMPT ? "" : `q=${encodeURIComponent(prompt)}&`;
        await rememberFolder(folder);
        await openUrl(`claude://code/new?${q}folder=${encodeURIComponent(folder)}`);
        toast(prompt.length > MAX_URL_PROMPT ? "Note copied — paste it into Claude Code" : "Opened in Claude — confirm the folder, then send");
      } else {
        await api.openInAgent(target === "claude-terminal" ? "claude" : "codex", note.id, folder);
        toast(`Started ${target === "claude-terminal" ? "Claude Code" : "Codex"} in ${basename(folder)}`);
      }
    });

  const chooseFolder = async (target: FolderTarget) => {
    const picked = await openDialog({ directory: true, multiple: false, title: "Choose a project folder", defaultPath: recent[0] });
    if (typeof picked === "string") await openWithFolder(target, picked);
  };

  const saveFile = () =>
    run(async () => {
      await flush();
      const safeName = note.title.replace(/[\\/:*?"<>|]+/g, " ").trim() || "note";
      const path = await saveDialog({ defaultPath: `${safeName}.md`, filters: [{ name: "Markdown", extensions: ["md"] }] });
      if (!path) return;
      await api.exportNote(note.id, path);
      toast(`Saved ${basename(path)}`);
    });

  const email = () =>
    run(async () => {
      await openUrl(`mailto:?subject=${encodeURIComponent(note.title)}&body=${encodeURIComponent(toPlainText(body))}`);
    });

  const item = (icon: IconName, label: string, onClick: () => void, hint?: string) => (
    <button className="popover-item" onClick={onClick}>
      <Icon name={icon} />
      <span>{label}</span>
      {hint && <span className="hint">{hint}</span>}
    </button>
  );

  if (folderTarget) {
    return (
      <div className="popover" role="menu">
        <button className="popover-item" onClick={() => setFolderTarget(null)}>
          <Icon name="back" />
          <strong>{FOLDER_TARGET_LABELS[folderTarget]}</strong>
        </button>
        <div className="popover-label">Project folder</div>
        {recent.map((folder) => (
          <button key={folder} className="popover-item folder" title={folder} onClick={() => openWithFolder(folderTarget, folder)}>
            <Icon name="folder" />
            <span>{basename(folder)}</span>
            <span className="hint">{folder}</span>
          </button>
        ))}
        {item("plus", "Choose folder…", () => void chooseFolder(folderTarget))}
      </div>
    );
  }

  return (
    <div className="popover" role="menu">
      <div className="popover-label">Copy</div>
      {item("copy", "Copy as prompt", () => copy(asPrompt(note, body), "Copied as a prompt — paste into Claude Code or Codex"), IS_MAC ? "⌘⇧C" : "Ctrl+Shift+C")}
      {item("copy", "Copy Markdown", () => copy(body, "Copied Markdown"))}
      {item("copy", "Copy plain text", () => copy(toPlainText(body), "Copied plain text"))}
      {item(
        "copy",
        "Copy note reference",
        () =>
          copy(
            `Use my sticky note "${note.title}" (stickies note id ${note.id}; in Claude Code: @stickies:note://${note.id}).`,
            "Copied — works in Claude Code / Codex when Stickies is connected",
          ),
        "MCP",
      )}

      <div className="popover-label">Start a session</div>
      {item("terminal", "Claude Code", () => setFolderTarget("claude-terminal"), "terminal ›")}
      {item("terminal", "Codex", () => setFolderTarget("codex-terminal"), "terminal ›")}
      {item("external", "Claude Code", () => setFolderTarget("claude-desktop-code"), "Claude app ›")}

      <div className="popover-label">Chat</div>
      {item("external", "Claude", () => openPrefilled((q) => `claude://claude.ai/new?q=${q}`, "claude://claude.ai/new", "Claude"), "Claude app")}
      {item("external", "ChatGPT", () => openPrefilled((q) => `https://chatgpt.com/?q=${q}`, "https://chatgpt.com/", "ChatGPT"), "browser")}

      <div className="popover-label">Share</div>
      {item("mail", "Email…", email)}
      {item("download", "Save as Markdown file…", saveFile)}
    </div>
  );
}

// src/SendMenu.vue
<script setup lang="ts">
import { onMounted, ref } from "vue";
import { writeText } from "@tauri-apps/plugin-clipboard-manager";
import { open as openDialog, save as saveDialog } from "@tauri-apps/plugin-dialog";
import { openUrl } from "@tauri-apps/plugin-opener";
import { api, errorText, type Note } from "./api";
import type { IconName } from "./icons";
import { asPrompt, toPlainText } from "./markdown";
import Icon from "./Icon.vue";

const props = defineProps<{
  note: Note;
  body: string;
  /** Save pending edits first, so handoffs that read the note file see them. */
  flush: () => Promise<void>;
}>();

const emit = defineEmits<{
  close: [];
  toast: [message: string, error?: boolean];
}>();

/** Claude Desktop truncates `q` at ~14k characters; stay well under for every target. */
const MAX_URL_PROMPT = 7000;
const IS_MAC = navigator.userAgent.includes("Mac");

type FolderTarget = "claude-terminal" | "codex-terminal" | "claude-desktop-code";

const FOLDER_TARGET_LABELS: Record<FolderTarget, string> = {
  "claude-terminal": "Claude Code in a terminal",
  "codex-terminal": "Codex in a terminal",
  "claude-desktop-code": "Claude Code in the Claude app",
};

const folderTarget = ref<FolderTarget | null>(null);
const recent = ref<string[]>([]);

onMounted(async () => {
  recent.value = (await api.getConfig()).recent_folders ?? [];
});

function basename(path: string) {
  return path.replace(/[\\/]+$/, "").split(/[\\/]/).pop() || path;
}

const toast = (message: string, error = false) => emit("toast", message, error);
const prompt = () => asPrompt(props.note, props.body);

async function run(action: () => Promise<void>) {
  try {
    await action();
    emit("close");
  } catch (e) {
    toast(errorText(e), true);
  }
}

function copy(text: string, message: string) {
  return run(async () => {
    await writeText(text);
    toast(message);
  });
}

/** Opens a prefilled URL; long notes go on the clipboard instead. */
function openPrefilled(buildUrl: (q: string) => string, bareUrl: string, app: string) {
  return run(async () => {
    const text = prompt();
    if (text.length > MAX_URL_PROMPT) {
      await writeText(text);
      await openUrl(bareUrl);
      toast(`Note is long, so it's on your clipboard — paste it into ${app}`);
    } else {
      await openUrl(buildUrl(encodeURIComponent(text)));
      toast(`Opened in ${app} — review and send`);
    }
  });
}

async function rememberFolder(folder: string) {
  const config = await api.getConfig();
  const folders = [folder, ...config.recent_folders.filter((f) => f !== folder)].slice(0, 6);
  await api.setConfig({ ...config, recent_folders: folders });
}

function openInFolder(folder: string) {
  const target = folderTarget.value;
  if (!target) return;
  return run(async () => {
    await props.flush();
    if (target === "claude-desktop-code") {
      const text = prompt();
      const tooLong = text.length > MAX_URL_PROMPT;
      if (tooLong) await writeText(text);
      await rememberFolder(folder);
      const q = tooLong ? "" : `q=${encodeURIComponent(text)}&`;
      await openUrl(`claude://code/new?${q}folder=${encodeURIComponent(folder)}`);
      toast(tooLong ? "Note copied — paste it into Claude Code" : "Opened in Claude — confirm the folder, then send");
    } else {
      const agent = target === "claude-terminal" ? "claude" : "codex";
      await api.openInAgent(agent, props.note.id, folder);
      toast(`Started ${agent === "claude" ? "Claude Code" : "Codex"} in ${basename(folder)}`);
    }
  });
}

async function chooseFolder() {
  const picked = await openDialog({ directory: true, multiple: false, title: "Choose a project folder", defaultPath: recent.value[0] });
  if (typeof picked === "string") await openInFolder(picked);
}

// Each entry is one row in the menu. To add a destination, add an item here.
interface SendItem {
  icon: IconName;
  label: string;
  hint?: string;
  action: () => unknown;
}

const sections: { label: string; items: SendItem[] }[] = [
  {
    label: "Copy",
    items: [
      {
        icon: "copy",
        label: "Copy as prompt",
        hint: IS_MAC ? "⌘⇧C" : "Ctrl+Shift+C",
        action: () => copy(prompt(), "Copied as a prompt — paste into Claude Code or Codex"),
      },
      { icon: "copy", label: "Copy Markdown", action: () => copy(props.body, "Copied Markdown") },
      { icon: "copy", label: "Copy plain text", action: () => copy(toPlainText(props.body), "Copied plain text") },
      {
        icon: "copy",
        label: "Copy note reference",
        hint: "MCP",
        action: () =>
          copy(
            `Use my sticky note "${props.note.title}" (stickies note id ${props.note.id}; in Claude Code: @stickies:note://${props.note.id}).`,
            "Copied — works in Claude Code / Codex when Stickies is connected",
          ),
      },
    ],
  },
  {
    label: "Start a session",
    items: [
      { icon: "terminal", label: "Claude Code", hint: "terminal ›", action: () => (folderTarget.value = "claude-terminal") },
      { icon: "terminal", label: "Codex", hint: "terminal ›", action: () => (folderTarget.value = "codex-terminal") },
      { icon: "external", label: "Claude Code", hint: "Claude app ›", action: () => (folderTarget.value = "claude-desktop-code") },
    ],
  },
  {
    label: "Chat",
    items: [
      {
        icon: "external",
        label: "Claude",
        hint: "Claude app",
        action: () => openPrefilled((q) => `claude://claude.ai/new?q=${q}`, "claude://claude.ai/new", "Claude"),
      },
      {
        icon: "external",
        label: "ChatGPT",
        hint: "browser",
        action: () => openPrefilled((q) => `https://chatgpt.com/?q=${q}`, "https://chatgpt.com/", "ChatGPT"),
      },
    ],
  },
  {
    label: "Share",
    items: [
      {
        icon: "mail",
        label: "Email…",
        action: () =>
          run(() => openUrl(`mailto:?subject=${encodeURIComponent(props.note.title)}&body=${encodeURIComponent(toPlainText(props.body))}`)),
      },
      {
        icon: "download",
        label: "Save as Markdown file…",
        action: () =>
          run(async () => {
            await props.flush();
            const safeName = props.note.title.replace(/[\\/:*?"<>|]+/g, " ").trim() || "note";
            const path = await saveDialog({ defaultPath: `${safeName}.md`, filters: [{ name: "Markdown", extensions: ["md"] }] });
            if (!path) return;
            await api.exportNote(props.note.id, path);
            toast(`Saved ${basename(path)}`);
          }),
      },
    ],
  },
];
</script>

<template>
  <div v-if="folderTarget" class="popover" role="menu">
    <button class="popover-item" @click="folderTarget = null">
      <Icon name="back" />
      <strong>{{ FOLDER_TARGET_LABELS[folderTarget] }}</strong>
    </button>
    <div class="popover-label">Project folder</div>
    <button v-for="folder in recent" :key="folder" class="popover-item folder" :title="folder" @click="openInFolder(folder)">
      <Icon name="folder" />
      <span>{{ basename(folder) }}</span>
      <span class="hint">{{ folder }}</span>
    </button>
    <button class="popover-item" @click="chooseFolder">
      <Icon name="plus" />
      <span>Choose folder…</span>
    </button>
  </div>

  <div v-else class="popover" role="menu">
    <template v-for="section in sections" :key="section.label">
      <div class="popover-label">{{ section.label }}</div>
      <button v-for="item in section.items" :key="`${item.label}-${item.hint}`" class="popover-item" @click="item.action">
        <Icon :name="item.icon" />
        <span>{{ item.label }}</span>
        <span v-if="item.hint" class="hint">{{ item.hint }}</span>
      </button>
    </template>
  </div>
</template>
